/**
 * Heuristic food-related matching for Vision label/object names.
 * Vision returns English phrases; we match substrings (lowercased).
 */
const FOOD_SUBSTRINGS = [
  'food',
  'dish',
  'meal',
  'cuisine',
  'cooking',
  'recipe',
  'gourmet',
  'delicacy',
  'snack',
  'vegetable',
  'fruit',
  'produce',
  'salad',
  'greens',
  'meat',
  'seafood',
  'fish',
  'chicken',
  'beef',
  'pork',
  'lamb',
  'turkey',
  'bacon',
  'sausage',
  'steak',
  'egg',
  'dairy',
  'cheese',
  'milk',
  'yogurt',
  'butter',
  'bread',
  'bun',
  'bagel',
  'croissant',
  'pastry',
  'muffin',
  'cake',
  'dessert',
  'pie',
  'cookie',
  'brownie',
  'donut',
  'doughnut',
  'chocolate',
  'candy',
  'chip',
  'crisp',
  'rice',
  'pasta',
  'noodle',
  'spaghetti',
  'pizza',
  'burger',
  'hamburger',
  'sandwich',
  'wrap',
  'taco',
  'burrito',
  'sushi',
  'ramen',
  'soup',
  'stew',
  'curry',
  'bowl',
  'porridge',
  'oatmeal',
  'cereal',
  'breakfast',
  'brunch',
  'lunch',
  'dinner',
  'fast food',
  'takeout',
  'coffee',
  'espresso',
  'latte',
  'cappuccino',
  'tea',
  'smoothie',
  'juice',
  'baked',
  'fried',
  'grilled',
  'roasted',
  'steamed',
  'boiled',
  'ingredient',
  'condiment',
  'sauce',
  'dip',
  'spread',
  'ice cream',
  'frozen yogurt',
  'apple',
  'banana',
  'orange',
  'berry',
  'grape',
  'tomato',
  'potato',
  'onion',
  'lettuce',
  'broccoli',
  'avocado',
  'mango',
  'citrus',
  'nut',
  'almond',
  'peanut',
  'tofu',
  'legume',
  'bean',
  'lentil',
  'quinoa',
  'waffle',
  'pancake',
  'baguette',
  'toast',
  'nugget',
  'hot dog',
  'sashimi',
  'tempura',
  'dumpling',
  'spring roll',
  'dim sum',
  'bento',
  'alcohol',
  'cocktail',
  'wine',
  'beer',
] as const;

/** Single-token labels that are almost never the food itself in meal photos. */
const STRONG_NON_FOOD_EXACT = new Set([
  'person',
  'people',
  'human',
  'face',
  'clothing',
  'footwear',
  'shoe',
  'furniture',
  'vehicle',
  'car',
  'electronics',
  'mobile phone',
  'laptop',
  'building',
  'ceiling',
  'wall',
  'floor',
  'sky',
  'cloud',
  'grass',
  'tree',
  'flower',
  'plant',
  'dog',
  'cat',
  'bird',
  'animal',
  'pet',
  'sport',
  'toy',
  'tableware',
  'cutlery',
  'fork',
  'knife',
  'spoon',
]);

export function isFoodRelatedLabel(description: string): boolean {
  const d = description.toLowerCase().trim();
  if (!d) return false;
  if (STRONG_NON_FOOD_EXACT.has(d)) return false;
  return FOOD_SUBSTRINGS.some((term) => d.includes(term));
}

export type ScoredName = { name: string; score: number };

/**
 * Keep food-like annotations with score >= minScore, dedupe by lowercase name (keep best score), top 3.
 */
export function filterRankTopFoodLabels(candidates: ScoredName[], minScore: number, topN: number): ScoredName[] {
  const byKey = new Map<string, ScoredName>();
  for (const c of candidates) {
    const name = c.name?.trim();
    if (!name || typeof c.score !== 'number' || !Number.isFinite(c.score)) continue;
    if (c.score < minScore) continue;
    if (!isFoodRelatedLabel(name)) continue;
    const key = name.toLowerCase();
    const prev = byKey.get(key);
    if (!prev || c.score > prev.score) {
      byKey.set(key, { name, score: c.score });
    }
  }
  return [...byKey.values()].sort((a, b) => b.score - a.score).slice(0, topN);
}
