import { StyleSheet } from 'react-native';

import type { AppThemeColors } from '@/constants/app-theme';
import { Fonts } from '@/constants/theme';
import { Palette } from '@/constants/palette';

/** Home dashboard styles keyed to light/dark semantic colors (design.md). */
export function createHomeDashboardStyles(c: AppThemeColors) {
  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: c.bg,
    },
    scroll: {
      paddingHorizontal: 20,
      paddingBottom: 100,
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginTop: 8,
      marginBottom: 20,
    },
    greeting: {
      fontFamily: Fonts.bold,
      fontSize: 28,
      lineHeight: 34,
      color: c.text,
    },
    dateLine: {
      fontFamily: Fonts.regular,
      fontSize: 15,
      color: c.textMuted,
      marginTop: 4,
    },
    streakCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      backgroundColor: c.streakBg,
      borderRadius: 18,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: c.border,
    },
    streakEmoji: { fontSize: 36 },
    streakBody: { flex: 1 },
    streakValue: { fontFamily: Fonts.bold, fontSize: 18, color: c.streakText },
    streakHint: {
      fontFamily: Fonts.regular,
      fontSize: 13,
      color: c.streakHint,
      marginTop: 4,
      lineHeight: 18,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    proBtn: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: c.iconWell,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: c.iconWellBorder,
    },
    menuBtn: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: c.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },
    calCard: {
      backgroundColor: c.surface,
      borderRadius: 24,
      padding: 22,
      marginBottom: 22,
      borderWidth: 1,
      borderColor: c.border,
      overflow: 'hidden',
    },
    calGlow: {
      position: 'absolute',
      top: -50,
      right: -30,
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: Palette.mist,
      opacity: 0.35,
    },
    calHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 18,
    },
    calBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: c.chipOnLight,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
    },
    calBadgeText: {
      fontFamily: Fonts.semiBold,
      fontSize: 12,
      color: Palette.iris,
      letterSpacing: 0.3,
    },
    calSyncSpinner: {
      marginLeft: 4,
      transform: [{ scale: 0.75 }],
    },
    statusChip: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
    },
    statusChipText: {
      fontFamily: Fonts.semiBold,
      fontSize: 11,
    },
    calHero: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    calConsumed: {
      fontFamily: Fonts.bold,
      fontSize: 40,
      lineHeight: 44,
      color: Palette.iris,
    },
    calGoal: {
      fontFamily: Fonts.bold,
      fontSize: 28,
      lineHeight: 32,
      color: c.text,
    },
    calLabel: {
      fontFamily: Fonts.regular,
      fontSize: 13,
      color: c.textMuted,
      marginTop: 2,
    },
    calDivider: {
      width: 1,
      height: 48,
      backgroundColor: c.calDivider,
      marginHorizontal: 20,
    },
    calProgressTrack: {
      height: 12,
      borderRadius: 999,
      overflow: 'hidden',
      marginBottom: 12,
    },
    calProgressFill: {
      height: '100%',
      borderRadius: 999,
    },
    calFoot: {
      fontFamily: Fonts.regular,
      fontSize: 14,
      color: c.textMuted,
    },
    calFootStrong: {
      fontFamily: Fonts.semiBold,
      color: c.text,
    },
    sectionHead: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
      marginTop: 6,
    },
    sectionTitle: {
      fontFamily: Fonts.bold,
      fontSize: 20,
      color: c.text,
    },
    sectionLink: {
      fontFamily: Fonts.semiBold,
      fontSize: 14,
      color: Palette.lavender,
    },
    macroCard: {
      flexDirection: 'row',
      backgroundColor: c.surface,
      borderRadius: 18,
      padding: 14,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: c.border,
      gap: 14,
      alignItems: 'center',
    },
    macroIconBlob: {
      width: 48,
      height: 48,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    macroCardBody: {
      flex: 1,
      minWidth: 0,
    },
    macroCardTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'baseline',
      marginBottom: 8,
    },
    macroName: {
      fontFamily: Fonts.semiBold,
      fontSize: 16,
      color: c.text,
    },
    macroNums: {
      fontFamily: Fonts.semiBold,
      fontSize: 15,
    },
    macroCurrent: {
      color: c.text,
    },
    macroSlash: {
      fontFamily: Fonts.regular,
      color: c.textMuted,
    },
    macroTrack: {
      height: 8,
      borderRadius: 999,
      overflow: 'hidden',
      marginBottom: 6,
    },
    macroFill: {
      height: '100%',
      borderRadius: 999,
    },
    macroRemain: {
      fontFamily: Fonts.regular,
      fontSize: 12,
      color: c.textMuted,
    },
    mealPlanLoading: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 24,
      paddingHorizontal: 4,
    },
    mealPlanLoadingText: {
      fontFamily: Fonts.regular,
      fontSize: 14,
      color: c.textMuted,
    },
    mealScroll: {
      paddingRight: 20,
      gap: 12,
      paddingBottom: 8,
    },
    mealCard: {
      backgroundColor: c.surface,
      borderRadius: 20,
      padding: 16,
      marginRight: 12,
      borderWidth: 1,
      borderColor: c.border,
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    mealAccent: {
      width: 52,
      height: 52,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    mealTag: {
      fontFamily: Fonts.semiBold,
      fontSize: 11,
      color: Palette.lavender,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 6,
    },
    mealTitle: {
      fontFamily: Fonts.bold,
      fontSize: 17,
      lineHeight: 22,
      color: c.text,
      marginBottom: 12,
      minHeight: 44,
    },
    mealMeta: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    mealMetaChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: c.chipOnLight,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
    },
    mealMetaText: {
      fontFamily: Fonts.medium,
      fontSize: 12,
      color: c.text,
    },
    groceryCard: {
      backgroundColor: c.surface,
      borderRadius: 24,
      padding: 18,
      marginTop: 20,
      borderWidth: 1,
      borderColor: c.border,
    },
    groceryHeader: {
      marginBottom: 8,
    },
    groceryTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    groceryIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: c.iconWell,
      alignItems: 'center',
      justifyContent: 'center',
    },
    groceryTitle: {
      fontFamily: Fonts.bold,
      fontSize: 18,
      color: c.text,
    },
    grocerySubtitle: {
      fontFamily: Fonts.regular,
      fontSize: 13,
      color: c.textMuted,
      marginTop: 2,
    },
    addListBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      marginTop: 14,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: c.chipOnLight,
      borderWidth: 1,
      borderColor: c.borderStrong,
    },
    addListText: {
      fontFamily: Fonts.semiBold,
      fontSize: 14,
      color: Palette.iris,
    },
  });
}
